### ISSUE TITLE
Links in API.md don't work

### ISSUE THREAD

**Issue by YizhePKU** [babashka/fs#109]
I propose we migrate from quickdoc to cljdoc for documentations.

Rationale:

* Quickdoc is currently somewhat broken (links don't work), and less familiar to new users
* Cljdoc produces [good result](https://cljdoc.org/d/babashka/fs/0.4.19/api/babashka.fs) without CI
* Multiple documentation systems complicates things (the repo currently has quickdoc, cljdoc, and codox).

I'm willing to submit a PR if this sounds like a good idea.

**Comment by borkdude** [comment]
Hi, I wrote and prefer quickdoc because I like having quick feedback and have a local-first system. If something doesn't work with quickdoc, please post an issue there. 
Additionally, if someone else wants to add cljdoc support, that would be fine with me!

**Comment by borkdude** [comment]
It's not because of quickdoc that the links in the table of contents don't work, it's because the Github UI changed. E.g if you click on create-link, the address bar will show https://github.com/babashka/fs/blob/master/API.md#babashka.fs/create-link but the UI won't navigate to there. But if you refresh the browser it does work. I'll file an issue with Github.

**Comment by borkdude** [comment]
Posted an issue here: https://github.com/orgs/community/discussions/62205

**Comment by borkdude** [comment]
If you don't mind I'll re-open this issue but I'll change the title about the malfunctioning links.

**Comment by borkdude** [comment]
A response from a ticket I posted in their non-public issue tracker:

<img width="1038" alt="Screenshot 2023-07-31 at 11 10 11" src="https://github.com/babashka/fs/assets/284934/658954a3-7d57-41b8-867c-6c1678bb90d4">

**Comment by borkdude** [comment]
This is now fixed by Github.
